# Please keep this as true in while using TCPShield!
only-allow-proxy-connections: true

# available modes: system (uses the system time), htpdate (uses a synchronized date) & off (deactivates timestamp validation)
timestamp-validation: 'htpdate'

# Turn on to diagnose connection issues
debug-mode: false

# Toggle to enable support for Geyser/Floodgate v2
enable-geyser-support: false

# Spigot/Paper option only, does not affect bungeecord
prefer-protocollib: false
